#!/usr/local/baize/env/bin/python
#coding:utf-8

# (c) 2016 , Tianbiao Zu <zutianbian@qq.com>
#
# 该文件是白泽自动化管理系统的一部分,是白泽系统web的自动工作脚本


###################################################################################################
import os
import sys
import time
import random
from gevent import monkey
monkey.patch_all()
import gevent
sys.path.append('/usr/local/baize/')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "baize.settings")
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
from API.API_web.plugins.work_manage import Work_Manage_Gray_Upgrade
from API.API_web.plugins.task_manage import Task_Manage_Gray_Upgrade
###################################################################################################

if __name__ == '__main__':
    time.sleep(random.randint(0, 59))
    work_manage_gray_update = Work_Manage_Gray_Upgrade()
    task_manage_gray_update = Task_Manage_Gray_Upgrade()
    gevent.joinall([
        gevent.spawn(work_manage_gray_update.start),
        gevent.spawn(task_manage_gray_update.start),
    ])
